### PR TITLE
chore: fix build

### PR DESCRIPTION
**Pull request by bethesque**
This adds a Github workflow to replace the Travis build (which we have found is not a viable option for Open Source projects any more for the Pact Foundation) and locks down the Celluloid dependency that was causing the build to break.

### CODE REVIEW

**Comment by bethesque** [comment]
Oh - just realised there's an open PR already to add the Github workflow. The one I added has a "continue on failure" for the "experimental" ones, but given that there's nothing to do after the tests anyway, it's not really necessary.

**Comment by rg-3** [comment]
Looks good to me.

**Review by seancribbs — APPROVED** [review]
Looks great. Does the experimental flag actually do something? The two that failed should be ignored, right?

**Comment by bethesque** [comment]
It would do something if there was a job after the test job (ie. that job would actually run). At the moment, it does nothing! It just happened to be in the workflow that I copied from one of my other projects, so I left it in there.

**Pull request merged**
