### PR TITLE
Lock gems

### PR DESCRIPTION
**Pull request by bethesque**
rake spec task needs certain versions of rspec/rake to work correctly.
Otherwise it may fail with the error: undefined method last_comment for Rake::Application
Without locks to stop major version changes being picked up, the build
will break when backwards incompatible changes are released by any of the gems

### CODE REVIEW

**Comment by bethesque** [comment]
The Gemfile.lock is not currently committed. One reason I can see not to is that at least one of us (me) develops on mac, and travis runs on linux, so the dependencies would be different due to this code in the Gemfile:

```
group :guard do
  gem 'guard-rspec'
  case RbConfig::CONFIG['host_os']
  when /darwin/
    gem 'rb-fsevent'
    # gem 'growl_notify'
    gem 'growl'
  when /linux/
    gem 'rb-inotify'
    gem 'libnotify'
  end
end
```

**Comment by petejohanson** [comment]
@seancribbs The conventional wisdom I've always followed (based on http://yehudakatz.com/2010/12/16/clarifying-the-roles-of-the-gemspec-and-gemfile/) is: Check in Gemfile.lock for applications, don't check in for gems/libraries.

I think better to leave out of the repo, and just lock down versions in the Gemfile.

**Comment by bethesque** [comment]
@Asmod4n it's just for the development gems. The run time dependencies for the webmachine gem are specified in the gemspec.

**Comment by bethesque** [comment]
Please note that I've also dropped tests for the unsupported rubies, and added 2.4.1.

**Comment by seancribbs** [comment]
I just want to thank you all for keeping this project alive. Great work! 😍

**Comment by bethesque** [comment]
I'm using webmachine for another open source project that's under active development, so it's in my best interests to keep it healthy!

**Pull request merged**
