### PR TITLE
Build tidiness

### LINKED ISSUE #230: Reel adapter/tests seam to be broken
@tarcieri if you got time, might you try to take a look at why all reel specs are failing?

### PR DESCRIPTION
**Pull request by rgarner**
* Nix `Object#timeout` deprecation warnings when building with 2.3.0
* Fix #230 by [not running Celluloid in backported mode](http://git.io/vJf3J)
* Fix a problem whereby `Socket#close` does not actually block on closing the socket. Ruby thinks it's closed, but the OS has it in a brief `TIME_WAIT` state. There's seemingly no good way of detecting this, so we combine `sleep`ing after close with reverting to `before(:all)` for adapter lint tests and having each adapter's server live for the duration of all `adapter_lint` tests instead of restarting on every test.
* Add 2.2.0/2.3.0 to Travis YML
* Fix `NoMethodError: undefined method `spec' for nil:NilClass` which occurred in various of Travis's rubies due to old bundler versions by updating bundler before build

### CODE REVIEW

**Comment by rgarner** [comment]
Oh my word, github, you really are in a mood tonight.

**Comment by seancribbs** [comment]
This looks good to me. Is there a reason not to have Ruby 2.2 in the build?

**Comment by rgarner** [comment]
No *good* reason, no. Really I was just avoiding it to try and make the build time more tolerable while still acknowledging latest stable.

**Comment by rfestag** [comment]
Should we wait for this to be merged into master before merging into other PRs (like #235), or would it be fine to pull in to them now to get tests passing?

**Comment by Asmod4n** [comment]
I am going to run this a couple times on travis now.
If it always succeeds ill merge them soonish ™️

**Comment by Asmod4n** [comment]
builds all the time, merge merge.

**Comment by Asmod4n** [comment]
Next step would be to extract all adapters except those shipped by ruby itself to be moved to different gems.

Could there be a way to load them automatically when needed? @seancribbs @rgarner

**Comment by rgarner** [comment]
screen shot 2016-04-24 at 09 15 19

The relief ... now to work out why Rubinius is such a pain and fix it.

**Comment by Asmod4n** [comment]
@rgarner i believe it will work when done it like i said back here: https://github.com/webmachine/webmachine-ruby/issues/196

**Pull request merged**
